---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-auth-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientID: AgCuaNigvdCgcn1e02n7IX2fYhVBfCJSkukpD3NXu0FXd7XScb9y8YSNC9I39aN0EpnUG2D0NiAC8wwY137d5oobv0Sa54i+AXKycOXps6u0BeZ0Ez+wkNEIgl2jNqLG93/3iEwMRGXsS5d6r2XPnFVWdW0pBpfns1uVU3MguCpaSOMpqyQOJgkpXp2PmRFQ6neM+clZ8Rgh8N7BUMoJtzxCSvQRJ0bp8WiqHJ9zbBjrXLr8VTNF7HY/CW9SFxF9RuqmdLdDYKiD1qx4LrzriqyahiRZLaO0+oJSNSKDHQcE+wkyXpR2nRyTYAPhNqYv4PJyNpxzaPtK2C8gnmoVU0gIbYnVycruKnUEoTNon2OI6GRkgtFdgQ1oGVyJfI+6l12sTUNKRkG4OERPaqcZI7+bQi8cKv2FT/GvfhnChBT1vVIox/6AhWF4HlQk/BBncLuOu/89iKjJ8rEOaMl/5nkX8pCN6zeUpTFBHpsIip2eY6hPceA1kafOa4OoLzgAf65jO4DANlu0DHPaid8bwPdfCTtyRFJgqe+kAeLTr4IYkHZWo+VHwrB1v9SYvx7zf3m343S6gfxKInG+rkO4P/nPAJxCiTs1S3Tl6W6faAPl6StUZg50sHoy+VYaaGKb3rc2qVqpL/PRlZiIiCtVaFoG7/WEZKcDsOJOs6ooiHFdYsasnzDJ8660a/rLEy8wK7DErdpWpoFdxQd2654ijvPJFYsX6g==
    dex.github.clientSecret: AgAAPKtGkdpmF2OnaMiadydl1oOO5MYyEw3a4tETw3ja74S0ZSmCZeqY4TfgBtTZIZxLvjt2L4hDO+Y1Cijj2z0banT0I8+6JZgQsOCrJwgSPMQ0zF+CIe7i2rH7l+p3WXvEG6yKxjGYF6MZ6YzTSwX2hpZO93/+MPLozu0kVk57z2duvDk9pBIqBdjaDAL962xv8/kco/3A0Y15dkfLU5Hru4hPuySq9SkjoDuBgt7nZ4DfJZf84hZP89pXJGoxbP9oU5EkiZS0H6zFN3NVqQ4qgikBDx7u9I2XzGI8m7sCHZSeEgYIV9DIoocoaQcO082Q7GwRztFWkt2FJZlnZJC364P0BAG/bNcF30WNgbtELsJGkQXvt4ow9bO7fXBnszIwypRBbZUje/zBn0HsBic9dkIyXfXr59t9HKBKsOgsB6MVg96pQRfC9meZ1gxYQtYoJPgT3DY8/Ro4LL5EfsgiTTaRcTM5LlQifinl2DiAGONtW40nMgos9JC10qo0GJnOauQtuqndTT7Sb6bmE2mxEIvk4HEIiy72jB2E26VcUU+ZyN8xwseG375sSJZfOObyJKat9XkbF9O/tKPRqEV4L7pNzmcmSNJXn7LFKV5+Mom+E5vHDSRj7MDPUQ72xSCOhz5pGg8mHZ4bPxL3iF2RKrLxgFkjADg05tLIRpY9a0UtfJ8FsM+vi8a2cP2eF0c55hOwc2w3ZWEkPRvNx6Rh9AACf7J4ecyOdWcXnisY7K07w4OxvVh+
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-auth-secret
      namespace: argocd
    type: Opaque
